### PR TITLE
Bugfix/102 escape special char in http auth

### LINKED ISSUE #102: HTTPClient: Special characters will not escaped in auth
Credentials with e.g. `$` does not work with the http client.

### PR DESCRIPTION
**Pull request by nhinze23**
Resolves #102

### CODE REVIEW

File: src/com/cloudogu/ces/cesbuildlib/HttpClient.groovy [hunk 1]
```diff
@@ -51,23 +51,23 @@ class HttpClient implements Serializable {
     }
 
     protected String getCurlAuthParam() {
-        "-u ${script.env.CURL_USER}:${script.env.CURL_PASSWORD}"
+        "-u '${script.env.CURL_USER}:${script.env.CURL_PASSWORD}'"
```
Comment (alexander-dammeier) [inline src/com/cloudogu/ces/cesbuildlib/HttpClient.groovy:54]: Check if this can be an security risk as the username can contain a single quote so that other evaluations like `${...}` can get injected. This can possibly be fixed by escaping quotes with a backslash or smth.

File: test/com/cloudogu/ces/cesbuildlib/HttpClientTest.groovy [hunk 2]
```diff
@@ -97,7 +97,7 @@ class HttpClientTest {
         
         http.get('http://url')
 
-        assertThat(scriptMock.actualShMapArgs[0]).isEqualTo('curl -i -X GET -u user:pw http://url')
+        assertThat(scriptMock.actualShMapArgs[0]).isEqualTo("curl -i -X GET -u 'user:pw' \'http://url\'")
```
Comment (alexander-dammeier) [inline test/com/cloudogu/ces/cesbuildlib/HttpClientTest.groovy:100]: The escape sequence seems to have no effect.
```suggestion
        assertThat(scriptMock.actualShMapArgs[0]).isEqualTo("curl -i -X GET -u 'user:pw' 'http://url'")
```

File: src/com/cloudogu/ces/cesbuildlib/HttpClient.groovy [hunk 3]
```diff
@@ -51,23 +51,23 @@ class HttpClient implements Serializable {
...
     }
 
     private String getCurlCommand(String httpMethod, String url, String contentType, String data) {
         return "curl -i -X ${httpMethod} " +
             (credentials ? "${getCurlAuthParam()} " : '') +
             (contentType ? "-H 'Content-Type: ${contentType}' " : '') +
             (data ? "-d '" + data + "' "  : '') +
-            "${url}"
+            "'${url}'"
```
Comment (alexander-dammeier) [inline src/com/cloudogu/ces/cesbuildlib/HttpClient.groovy:62]: Also check this (and the one below) for injection vulnerabilities and e.g. escape the sequence.

**Review by alexander-dammeier — CHANGES_REQUESTED** [review]

**Review by jelemux — APPROVED** [review]
LGTM!
