### PR TITLE
Switch to hadolint Dockerfile linter

### LINKED ISSUE #111: Dockerfile linter is old and broken sometimes
The [dockerfile_lint](https://github.com/projectatomic/dockerfile_lint) command used in the `lintDockerfile` function of this lib throws an error if there is a `USER 1000:1000` line in the checked Dockerfile. It also is really old.

### PR DESCRIPTION
**Pull request by robertauer**
### Changed
- Switch to hadolint Dockerfile linter; #111

### Added
- Add Dockerfile class with new linting functions; #111
  - `lint()` lints with default hadolint config parameters. Only fails on errors
  - `lintWithConfig()` lets you specify the hadolint configuration

### Deprecated
- `lintDockerfile()` function should be replaced by the Dockerfile `lint()` function

Resolves #111

### CODE REVIEW

File: src/com/cloudogu/ces/cesbuildlib/Dockerfile.groovy [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+     * Lints the Dockerfile with hadolint using a configuration file
+     *
+     * To configure hadelint, add a ".hadolint.yaml" file to your working directory
+     * See https://github.com/hadolint/hadolint#configure
+     *
+     * @param dockerfile Path to the Dockerfile that should be linted
+     * @param configuration Path to the hadolint configuration file
+     */
+    void lintWithConfig(String dockerfile = "Dockerfile", String configuration = ".hadolint.yaml"){
+        script.docker.image('hadolint/hadolint:latest-debian').inside(){
```
Comment (jelemux) [inline src/com/cloudogu/ces/cesbuildlib/Dockerfile.groovy:20]: Maybe extract the version into a variable and make it configurable. If something breaks in the latest version, we can then easily swap to an earlier version.

**Review by jelemux — CHANGES_REQUESTED** [review]

File: src/com/cloudogu/ces/cesbuildlib/Dockerfile.groovy (hunk 1 above)
Comment (robertauer) [reply src/com/cloudogu/ces/cesbuildlib/Dockerfile.groovy]: Done

**Review by jelemux — APPROVED** [review]
LGTM!
